# Changie configuration for Watchtower changelog management
# https://changie.dev/

# Changelog file settings
changesDir: .changes
unreleasedDir: unreleased
headerPath: header.tpl.md
changelogPath: CHANGELOG.md
versionExt: md
versionFormat: '## {{.Version}} - {{.Time.Format "2006-01-02"}}'
kindFormat: '### {{.Kind}}'
changeFormat: '- {{.Body}} {{with .Issue}}([#{{.}}](https://github.com/i4o-oss/watchtower/issues/{{.}})){{end}}'

# Version settings
versionHeaderPath: ""
versionFooterPath: ""

# Change kinds (categories)
kinds:
  - label: "🚀 New Features"
    key: "added"
    auto: "feat"
  
  - label: "🐛 Bug Fixes"
    key: "fixed"
    auto: "fix"
  
  - label: "⚡ Performance Improvements"
    key: "performance"
    auto: "perf"
  
  - label: "🔒 Security"
    key: "security"
    auto: "security"
  
  - label: "📚 Documentation"
    key: "docs"
    auto: "docs"
    skipGlobalChoices: true
  
  - label: "🧹 Maintenance"
    key: "maintenance"
    auto: "chore"
    skipGlobalChoices: true
  
  - label: "🔄 Refactoring"
    key: "refactor"
    auto: "refactor"
    skipGlobalChoices: true
  
  - label: "🗑️ Deprecated"
    key: "deprecated"
    skipGlobalChoices: true
  
  - label: "❌ Removed"
    key: "removed"
    skipGlobalChoices: true

# Custom fields for changes
custom:
  - key: Author
    label: Author
    type: string
    minLength: 3
  
  - key: Issue
    label: GitHub Issue
    type: int
    
  - key: PR
    label: Pull Request
    type: int

# Replacements for common commit prefixes
replacements:
  - path: body
    find: '/^(feat|fix|perf|docs|chore|refactor|security)(\(.+?\))?: (.+)/'
    replace: '$3'

# Project settings
projectName: Watchtower
githubURL: https://github.com/i4o-oss/watchtower

# Environment settings
envPrefix: 'CHANGIE_'